Feat/gitr pull in clone if repo exists
plantoncloud/gitr pull request #43
Opened 2021-09-04 10:54 UTC by venky333

* Git pull for an existing repository.
* deletes the created folder (only repo folder) for cloning in local system.

2021-09-08 13:44 UTC, swarupdonepudi requested changes
thanks for the mr @venky333 ... mostly looks good but i posted a few suggestions around code quality and also some design choices. supporting https clone with access token and also implementing git pull sounds very useful. However, i suggest break the pr into two prs i.e support for https clone using access token should be one pr and supporting pull should be a different pr.

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +			return err
always use errors.Wrap() to bump the error to the caller with additional context

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +		log.Warn("your laptop is not configured with personal access token of git\n")
`\n` is not required with log statements. the logging library will print each log event in its own line

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +			"####################################################")
instead of having the user create the file, may be gitr can help simplify that for the user by having a subcommand to do that?

add a new token - `gitr token add --host gitlab.com --token "some-secret-token"`

show the token for a host - `gitr token get --host gitlab.com`

list all tokens for all hosts - `gitr token list`

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/common.go
> +func Remove(path string) error {
this wrapper function seems redundant. the caller should simply use the os.Remove method instead of this wrapper as it is not adding any value.

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +func gitPullHelper(path string, auth transport.AuthMethod) error {
the name of the method should reflect what that method accomplishes. Helper functions are very ambiguous in the sense that they dont clearly reflect what they really do when the name says `Helper`. i suggest either renaming this method to a verb to breaking down the function into more verbs.

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	if err := os.Chdir(path); err != nil {
i dont think this will work. a process can not change the working directory of the parent process. refer to this https://github.com/swarupdonepudi/gitr/pull/30#issue-909798216

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +		return err
errors.Wrap always.

2021-09-08 13:44 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	err = w.Pull(&git.PullOptions{RemoteName: "origin",
does this pull the changes in all branches or only the checked out branch?

2021-09-10 01:32 UTC, venky333 commented on pkg/clone/clone.go
> +		log.Warn("your laptop is not configured with personal access token of git\n")
True. I wanted this logs to be noticed by user. So having a space will bring notice to the eye. So keep it that way. I will remove it.

2021-09-10 01:36 UTC, venky333 commented on pkg/clone/clone.go
> +			"####################################################")
User is not creating any file here. User needs to create a secret token in gitlab/hub and provide the token in the clone command. gitr will create a file in his/her local system and will use it from next time.
If user gives another token in the next clone command, previous one in his/her local system will be overridden if it exists.

This way I think, user need not do much of the work. It simplifies his/her work.

* listing all the token using gitr sounds like a good idea. Will implement it as a new feature. What do you think ?

2021-09-10 04:17 UTC, swarupdonepudi approved these changes

2021-09-14 12:43 UTC, venky333 commented on pkg/common.go
> +func Remove(path string) error {
actually, while going through the code, it is not readable with all the error check and then returning errors. So, if we move them to separate functions like these, code in the main block is more readable. What do you think ?

2021-09-14 12:53 UTC, venky333 commented on pkg/clone/clone.go
> +func gitPullHelper(path string, auth transport.AuthMethod) error {
done

2021-09-14 12:58 UTC, venky333 commented on pkg/clone/clone.go
> +	err = w.Pull(&git.PullOptions{RemoteName: "origin",
pull it into current branch

2021-09-14 13:14 UTC, venky333 commented on pkg/clone/clone.go
> +	if err := os.Chdir(path); err != nil {
Ok. Thanks for the info. In this case, it is really not necessary. I added it as a double check to check whether the dir exists before pulling the latest data. Removing it :)

2021-09-29 12:18 UTC, swarupdonepudi commented on pkg/common.go
> +func Remove(path string) error {
i went down the same path and added a bunch of wrapper functions but these wrapper functions also return an error which needs to be handled where ever you call this. so i moved away from this pattern and started to simply use the original functions. recommend the same.

2021-09-29 12:50 UTC, swarupdonepudi commented on cmd/gitr/clone.go
> +	if len(args) > 1 {
token should not be read from args but instead be read from flags.

2021-09-29 12:50 UTC, swarupdonepudi commented on cmd/gitr/clone.go
> +	if err := clone.Clone(cfg, inputUrl, token, creDir, dry); err != nil {
`Clone` is an exported function which makes it part of the module api that can be consumed by others. Adding an additional argument would break the existing users of the api. for now its not a big deal but do remember that changes to public api should be backward compatible.

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +		log.Info("repo already exists. pulling the latest changes from origin")
what happens if there are uncommitted changes on the current branch?

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	pAccessTokenDir := fmt.Sprintf("%s/.personal_access_tokens", homeDir)
use filepath.Join()

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	homeDir, _ := os.UserHomeDir()
never swallow any errors. they will lead to ugly panics. although seems like this particular function never fails, it might.

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	}
in golang it is recommended not to write if..else and replace with multiple if statements. the above can be written as

```golang
if inputToken != "" {
  // create dir
  // write token to file
}
//at this point you know for sure that pAccessTokenFileAbsPath exists.. so no checks needed
pem, err := ioutil.ReadFile(pAccessTokenFileAbsPath)
if err != nil {
	return nil, errors.Wrapf(err, "failed to read %s", pAccessTokenFileAbsPath)
}
token := string(pem[:])
return &token, nil
```

notice the reduced conditional statements which would reduce the cognitive load

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +			if err != nil {
you are not handling the error returned by the previous statement here... a common mistake.

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +			token := string(pem[:])
this statement is hard to read. mind moving the logic to read the token from a file to a diff func so that it is testable?

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	return nil
same comment as above

```golang
{
	if !url.IsGitUrl(repoUrl) {
		log.Infof("gitr supports pull only for git")
		return nil
	}
	var auth transport.AuthMethod
	if url.IsGitSshUrl(repoUrl) {
		auth, err = setUpSshAuth(url.GetHostname(repoUrl))
		if err != nil {
			return errors.Wrap(err, "ssh auth setup failed")
		}
	} else {
		token, err := setUpHttpsPersonalAccessToken(url.GetHostname(repoUrl), "")
		if err != nil {
			return errors.Wrap(err, "error setting up personal access token")
		}
		auth = &http.BasicAuth{
			Username: "non-empty-string", // this can be anything except an empty string
			Password: *token,
		}
	}
	if err := gitPullAndPrintLatestCommitObject(clonePath, auth); err != nil {
		return errors.Wrap(err, "failed to git pull")
	}
	return
}
```

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	return nil
essentially the code becomes readable from top to bottom.

```
if not a git url -> return
setup auth on a conditional
call git pull
```

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	return nil
notice that i have used [named return values ](https://tour.golang.org/basics/7)i.e `(err error)`

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +		if err.Error() == "already up-to-date" {
same as above... 

```golang
if err != nil && err.Error() == "already up-to-date" {
   return nil
}
```

do not add print statements inside the function. a good practice that i learnt while writing clis

2021-09-29 12:50 UTC, swarupdonepudi commented on pkg/clone/clone.go
> +	fmt.Println(commit)
do not print inside functions. instead return this string and the caller will decide if they want to print. writing output to console is not the purpose of this func

2021-10-03 14:59 UTC, venky333 commented on pkg/common.go
> +func Remove(path string) error {
done

2021-10-03 15:40 UTC, venky333 commented on cmd/gitr/clone.go
> +	if len(args) > 1 {
removed this logic and adding token will be added via flag as new feature

2021-10-04 07:56 UTC, venky333 commented on pkg/clone/clone.go
> +	pAccessTokenDir := fmt.Sprintf("%s/.personal_access_tokens", homeDir)
done

2021-10-08 05:42 UTC, venky333 commented on pkg/clone/clone.go
> +	homeDir, _ := os.UserHomeDir()
done

2021-10-08 05:43 UTC, venky333 commented on pkg/clone/clone.go
> +	}
done

2021-10-08 05:43 UTC, venky333 commented on pkg/clone/clone.go
> +			if err != nil {
done

2021-10-09 07:08 UTC, venky333 commented on pkg/clone/clone.go
> +			token := string(pem[:])
modified

2021-10-10 06:39 UTC, venky333 commented on pkg/clone/clone.go
> +	return nil
interesting and good one. Thanks. Done.

2021-10-10 06:56 UTC, venky333 commented on pkg/clone/clone.go
> +		if err.Error() == "already up-to-date" {
in this case error might not be `already up-to-date`. So handling it with one layer of nested if like below.

`	
if err != nil {
    if err.Error() != "already up-to-date" {
	    return errors.Wrap(err, "error while pulling the latest from git")
    }
    return nil
}
`

2021-10-10 06:57 UTC, venky333 commented on pkg/clone/clone.go
> +	fmt.Println(commit)
done. changed it to log

2021-10-10 08:19 UTC, venky333 commented on pkg/clone/clone.go
> +		log.Info("repo already exists. pulling the latest changes from origin")
command will return error stating that `error occurred during pull`

2021-11-20 01:26 UTC, venky333 commented
@swarupdonepudi please review this pr.

2023-07-12 18:04 UTC, closed without merging